export interface FoodItem {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  description: string;
  category: "salads" | "sandwich" | "brunch" | "pizza" | "burger" | "fried-chicken" | "dessert";
  rating: number;
  reviews: number;
  popular: boolean;
  spicy?: boolean;
  vegetarian?: boolean;
  ingredients: string[];
  cookingTime: string;
  calories: number;
  emoji: string;
  specialOffer?: boolean;
  tags?: string[];
  pairings?: number[]; // IDs of food items that pair well
}

export const foodDatabase: FoodItem[] = [
  // Salads
  {
    id: 1,
    name: "Smoked Salmon",
    price: 50000,
    image: "/salads/smoked salmon salad.jpeg",
    description: "edamame, smoked salmon, Avocado, orange slices and dresses with a citrus sauce",
    category: "salads",
    rating: 4.5,
    reviews: 100,
    popular: true,
    vegetarian: false,
    ingredients: ["Edamame", "Smoked Salmon", "Avocado", "Orange Slices", "Citrus Sauce"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥗",
  },
  {
    id: 2,
    name: "Beetroot Salad",
    price: 50000,
    image: "/salads/beetroot salad.jpeg",
    description: "A vibrant and elegant salad featuring tender roasted beetroots paired with creamy fetaa cheese, crunchy toasted walnuts, and fresh mixed greens. Lightly dressed with a honey-balsamic vinaigrette, this dish balances earthy sweetness with tangy richness.",
    category: "salads",
    rating: 4.5,
    reviews: 100,
    popular: true,
    vegetarian: true,
    ingredients: ["Beetroots", "Feta Cheese", "Walnuts", "Mixed Greens", "Honey-Balsamic Vinaigrette"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥗",
  },
  {
    id: 3,
    name: "Greek Salad",
    price: 50000,
    image: "/salads/greek salad.jpeg",
    description: "tomatoes, cucumber, onions feta cheese, olives and dresses with a herbal sauce",
    category: "salads",
    rating: 4.5,
    reviews: 100,
    popular: true,
    vegetarian: true,
    ingredients: ["Tomatoes", "Cucumber", "Onions", "Feta Cheese", "Olives", "Herbal Sauce"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥗",
  },
  {
    id: 4,
    name: "Fatouch",
    price: 50000,
    image: "https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "radish, rocca, tomatoes, cucumber and dressed with a pomegranate sauce.",
    category: "salads",
    rating: 4.5,
    reviews: 100,
    popular: true,
    vegetarian: true,
    ingredients: ["Radish", "Rocca", "Tomatoes", "Cucumber", "Pomegranate Sauce"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥗",
  },

  // Sandwich
  {
    id: 5,
    name: "Scrambled egg",
    price: 240,
    image: "/sandwich/scrambled egg.jpeg",
    description: "Eggs, avocado, bresaola/ bacon, cheddar cheese, onions",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Eggs", "Avocado", "Bresaola/Bacon", "Cheddar Cheese", "Onions"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },
  {
    id: 6,
    name: "Quatro",
    price: 285,
    image: "https://images.pexels.com/photos/1647163/pexels-photo-1647163.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Brie, swiss cheese, cheddar & Blue cheese",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Brie", "Swiss Cheese", "Cheddar", "Blue Cheese"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },
  {
    id: 7,
    name: "Reuben",
    price: 255,
    image: "https://images.pexels.com/photos/1647163/pexels-photo-1647163.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Bresaola, caramelized onions, swiss cheese & mustard",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Bresaola", "Caramelized Onions", "Swiss Cheese", "Mustard"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },
  {
    id: 8,
    name: "Greene Grilled",
    price: 255,
    image: "https://images.pexels.com/photos/1647163/pexels-photo-1647163.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "cheddar, emmental, bacon, avocado & cilantro sauce",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Cheddar", "Emmental", "Bacon", "Avocado", "Cilantro Sauce"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },
  {
    id: 9,
    name: "Smoked Salmon Sandwich",
    price: 465,
    image: "/sandwich/smoked salmon sandwich.jpeg",
    description: "Smoked salmon, brie cheese, swiss cheese, caramelized onions.",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Smoked Salmon", "Brie Cheese", "Swiss Cheese", "Caramelized Onions"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },
  {
    id: 10,
    name: "EL GRECO special",
    price: 265,
    image: "/sandwich/elgreko special.jpeg",
    description: "scrambled eggs, bacon, mix cheese, pickled peppers",
    category: "sandwich",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Scrambled Eggs", "Bacon", "Mix Cheese", "Pickled Peppers"],
    cookingTime: "15 mins",
    calories: 400,
    emoji: "🥪",
  },

  // Brunch
  {
    id: 11,
    name: "Pancake",
    price: 280,
    image: "/brunch/pancake.jpeg",
    description: "two eggs fried, bacon, pancake & fruits",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Eggs", "Bacon", "Pancake", "Fruits"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 12,
    name: "Crepe",
    price: 280,
    image: "/brunch/crepe.jpeg",
    description: "two fried eggs, smoked ham, swiss cheese & fruits",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Eggs", "Smoked Ham", "Swiss Cheese", "Fruits"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 13,
    name: "Sunshine",
    price: 280,
    image: "/brunch/sunshine.jpeg",
    description: "two fried eggs, bacon, crepe filled with cream & fruits",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Eggs", "Bacon", "Crepe", "Cream", "Fruits"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 14,
    name: "El Greco Special Brunch",
    price: 320,
    image: "/brunch/elgreco special brunch.jpeg",
    description: "two fried eggs, two waffle, bacon or Bresaola, cheese & fruits",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Eggs", "Waffle", "Bacon/Bresaola", "Cheese", "Fruits"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 15,
    name: "Benedict Classic",
    price: 260,
    image: "/brunch/benedict classic.jpeg",
    description: "two poached eggs, bacon/ turkey with Hollandaise sauce",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Poached Eggs", "Bacon/Turkey", "Hollandaise Sauce"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 16,
    name: "Copenhagen Benedict",
    price: 450,
    image: "/brunch/copenhagen benedict.jpeg",
    description: "two poached eggs, smoked salmon with hollandaise sauce",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Poached Eggs", "Smoked Salmon", "Hollandaise Sauce"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 17,
    name: "Cheese Omelet",
    price: 260,
    image: "/brunch/cheese omelet.jpeg",
    description: "swiss cheese, white cheese & waffle",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: ["Swiss Cheese", "White Cheese", "Waffle"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 18,
    name: "Veggie Omelet",
    price: 240,
    image: "/brunch/veggie omelet.jpeg",
    description: "peppers, mushrooms, spinach, onions & Waffle",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: ["Peppers", "Mushrooms", "Spinach", "Onions", "Waffle"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 19,
    name: "Portobello Omelet",
    price: 280,
    image: "/brunch/portobello omelet.jpeg",
    description: "prosciutto, mushrooms, pecorino romano cheese & waffle",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Prosciutto", "Mushrooms", "Pecorino Romano Cheese", "Waffle"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 20,
    name: "Cheese Pie",
    price: 150,
    image: "/brunch/cheese pie.jpeg",
    description: "",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: ["Cheese"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 21,
    name: "Thyme Pie",
    price: 100,
    image: "/brunch/thyme pie.jpeg",
    description: "",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: ["Thyme"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 22,
    name: "Meat Pie",
    price: 200,
    image: "/brunch/meat pie.jpeg",
    description: "",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Meat"],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 23,
    name: "Foul",
    price: 250,
    image: "/brunch/foul.jpeg",
    description: "",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: [],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },
  {
    id: 24,
    name: "Labneh",
    price: 150,
    image: "/brunch/labneh.jpeg",
    description: "",
    category: "brunch",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: [],
    cookingTime: "20 mins",
    calories: 500,
    emoji: "🥞",
  },

  // Pizzas
  {
    id: 25,
    name: "Margherita",
    price: 240,
    image: "/pizza/magherita.jpeg",
    description: "Tomatoes, mozarella, fresh rocca",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: true,
    vegetarian: true,
    ingredients: ["Tomatoes", "Mozzarella", "Fresh Rocca"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },
  {
    id: 26,
    name: "Chicken Pizza",
    price: 265,
    image: "/pizza/chicken pizza.jpeg",
    description: "spicy boneless chicken, cheese, mushrooms",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: false,
    spicy: true,
    ingredients: ["Spicy Boneless Chicken", "Cheese", "Mushrooms"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },
  {
    id: 27,
    name: "Quatro Pizza",
    price: 275,
    image: "/pizza/quatro pizza.jpeg",
    description: "emmental, gouda, blue cheese, mozzarella",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: false,
    vegetarian: true,
    ingredients: ["Emmental", "Gouda", "Blue Cheese", "Mozzarella"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },
  {
    id: 28,
    name: "Pepperoni",
    price: 275,
    image: "/pizza/pepperoni.jpeg",
    description: "pepperoni, cheese",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Pepperoni", "Cheese"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },
  {
    id: 29,
    name: "Sea food",
    price: 325,
    image: "/pizza/sea food.jpeg",
    description: "sea food mix, cheese",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Sea Food Mix", "Cheese"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },
  {
    id: 30,
    name: "Smoked Salmon Pizza",
    price: 400,
    image: "/pizza/smoked salmon pizza.jpeg",
    description: "smoked salmon, capers, rocca, cheese",
    category: "pizza",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Smoked Salmon", "Capers", "Rocca", "Cheese"],
    cookingTime: "25 mins",
    calories: 600,
    emoji: "🍕",
  },

  // Burger
  {
    id: 31,
    name: "Chicken burger",
    price: 250,
    image: "/burgers/chicken burger.jpeg",
    description: "Served with Fries",
    category: "burger",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Chicken Patty", "Bun", "Fries"],
    cookingTime: "20 mins",
    calories: 700,
    emoji: "🍔",
  },
  {
    id: 32,
    name: "Fish Burger",
    price: 250,
    image: "/burgers/fish burger.jpeg",
    description: "Served with Fries.",
    category: "burger",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Fish Patty", "Bun", "Fries"],
    cookingTime: "20 mins",
    calories: 700,
    emoji: "🍔",
  },

  // Fried Chicken
  {
    id: 33,
    name: "Wise 2",
    price: 225,
    image: "/fried-chicken/wise 2.jpeg",
    description: "2 pcs of Crispy fried chicken served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Fried Chicken", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 34,
    name: "wise 3",
    price: 255,
    image: "/fried-chicken/wise 3.jpeg",
    description: "3 pcs of Crispy fried chicken served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Fried Chicken", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 35,
    name: "wise 4",
    price: 305,
    image: "/fried-chicken/wise 4.jpeg",
    description: "4 pcs of Crispy fried chicken served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Fried Chicken", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 36,
    name: "wise 5",
    price: 365,
    image: "/fried-chicken/wise 5.jpeg",
    description: "5 pcs of Crispy fried chicken served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Fried Chicken", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 37,
    name: "Family",
    price: 680,
    image: "/fried-chicken/family.jpeg",
    description: "10 pcs of Crispy fried chicken served with two side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Fried Chicken", "Side Dishes"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 38,
    name: "Combo",
    price: 580,
    image: "/fried-chicken/combo.jpeg",
    description: "1 pc of chicken, fries & coleslaw",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Chicken", "Fries", "Coleslaw"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 39,
    name: "Strips",
    price: 225,
    image: "/placeholder.svg",
    description: "3 pcs of chicken strips served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Chicken Strips", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },
  {
    id: 40,
    name: "Wings",
    price: 225,
    image: "/placeholder.svg",
    description: "4 pcs of chicken wings served with one side dish",
    category: "fried-chicken",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Chicken Wings", "Side Dish"],
    cookingTime: "20 mins",
    calories: 800,
    emoji: "🍗",
  },

  // Dessert
  {
    id: 41,
    name: "Waffle",
    price: 150,
    image: "/desserts/waffle.jpeg",
    description: "Served with chocolate sauce and 1 topping.",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Waffle", "Chocolate Sauce", "Topping"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🧇",
  },
  {
    id: 42,
    name: "Donut Custard",
    price: 100,
    image: "/desserts/donut custard.jpeg",
    description: "Filled with custard and topped with chocolate",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Donut", "Custard", "Chocolate"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍩",
  },
  {
    id: 43,
    name: "Donut Plain",
    price: 80,
    image: "/desserts/donut plain.jpeg",
    description: "Topped with sugar",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Donut", "Sugar"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍩",
  },
  {
    id: 44,
    name: "Croissants",
    price: 100,
    image: "/desserts/croissants.jpeg",
    description: "Plain, chocolate or cheese",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Croissant"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥐",
  },
  {
    id: 45,
    name: "Banana Bread",
    price: 120,
    image: "/desserts/banana bread.jpeg",
    description: "Served with walnuts",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Banana", "Walnuts"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍌",
  },
  {
    id: 46,
    name: "Crepe Chocolate",
    price: 150,
    image: "/desserts/crepe chocolate.jpeg",
    description: "Served with chocolate sauce and 1 topping.",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Crepe", "Chocolate Sauce", "Topping"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🥞",
  },
  {
    id: 47,
    name: "Muffin",
    price: 100,
    image: "https://images.pexels.com/photos/265393/pexels-photo-265393.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Chocolate, blueberry or plain",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Muffin"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🧁",
  },
  {
    id: 48,
    name: "Ice Cream",
    price: 90,
    image: "https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Vanilla Ice cream served with a waffle and 1 topping.",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: ["Vanilla Ice Cream", "Waffle", "Topping"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍦",
  },
  {
    id: 49,
    name: "Cheese cake",
    price: 180,
    image: "/desserts/cheese cake.jpeg",
    description: "Cream cheese, with our seasonal flavors",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Cream Cheese", "Seasonal Flavors"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍰",
  },
  {
    id: 50,
    name: "Lazy Cake",
    price: 120,
    image: "/desserts/lazy cake.jpeg",
    description: "",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: [],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍰",
  },
  {
    id: 51,
    name: "Lemon Tart",
    price: 120,
    image: "/desserts/lemon tart.jpeg",
    description: "",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: ["Lemon"],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍋",
  },
  {
    id: 52,
    name: "Creme brulee",
    price: 120,
    image: "/desserts/creme bruele.jpeg",
    description: "",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: true,
    ingredients: [],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍮",
  },
  {
    id: 53,
    name: "Panna Cotta",
    price: 120,
    image: "https://images.pexels.com/photos/2144200/pexels-photo-2144200.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Indulge your taste buds with this delicious Italian dessert",
    category: "dessert",
    rating: 4.5,
    reviews: 100,
    popular: false,
    ingredients: [],
    cookingTime: "10 mins",
    calories: 300,
    emoji: "🍮",
  },
]

export const getFoodsByCategory = (category: string) => {
  if (category === "all") return foodDatabase
  return foodDatabase.filter((item) => item.category === category)
}

export const getPopularFoods = () => {
  return foodDatabase.filter((item) => item.popular).slice(0, 6)
}

export const getFoodById = (id: number) => {
  return foodDatabase.find((item) => item.id === id)
}

export const searchFoods = (query: string) => {
  return foodDatabase.filter(
    (item) =>
      item.name.toLowerCase().includes(query.toLowerCase()) ||
      item.description.toLowerCase().includes(query.toLowerCase()) ||
      item.ingredients.some((ingredient) => ingredient.toLowerCase().includes(query.toLowerCase())),
  )
}

export const getSpecialOffers = () => {
  return foodDatabase.filter(item => item.specialOffer);
}

import Fuse from 'fuse.js';

const fuseOptions = {
  threshold: 0.45, // Slightly tightened threshold, as tags provide accuracy
  keys: [
    { name: 'tags', weight: 0.4 }, // Tags are now the most important field
    { name: 'name', weight: 0.3 },
    { name: 'description', weight: 0.2 },
    { name: 'ingredients', weight: 0.1 },
  ],
};

export interface RecommendationFilters {
  isVegetarian?: boolean;
  isSpicy?: boolean;
  isPopular?: boolean;
}

export function recommendFoods(query: string, filters: RecommendationFilters): FoodItem[] {
  let results: FoodItem[] = [...foodDatabase];

  // 1. Apply filters
  if (filters.isVegetarian) {
    results = results.filter(item => item.vegetarian);
  }
  if (filters.isSpicy) {
    results = results.filter(item => item.spicy);
  }
  if (filters.isPopular) {
    results = results.filter(item => item.popular);
  }

  // 2. Apply fuzzy search if a query is provided
  if (query.trim()) {
    const fuse = new Fuse(results, fuseOptions);
    results = fuse.search(query).map(result => result.item);
  } else {
    // If no query, sort the filtered list by popularity
    results.sort((a, b) => (b.rating * b.reviews) - (a.rating * a.reviews));
  }

  return results.slice(0, 10);
}

// Removed getFoodItemById as it's a duplicate of getFoodById
// Use getFoodById instead for consistency
