export interface FoodItem {
  id: number
  name: string
  price: number
  originalPrice?: number
  image: string
  description: string
  category: "starters" | "mains" | "desserts" | "drinks"
  rating: number
  reviews: number
  popular: boolean
  spicy?: boolean
  vegetarian?: boolean
  ingredients: string[]
  cookingTime: string
  calories: number
  emoji: string
  specialOffer?: boolean
}

export const foodDatabase: FoodItem[] = [
  // Starters
  {
    id: 1,
    name: "Greek Village Salad",
    price: 35000,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=400&fit=crop",
    description: "Fresh tomatoes, cucumbers, olives, feta cheese with authentic Greek olive oil dressing",
    category: "starters",
    rating: 4.8,
    reviews: 124,
    popular: true,
    vegetarian: true,
    ingredients: ["Tomatoes", "Cucumbers", "Red Onions", "Feta Cheese", "Kalamata Olives", "Olive Oil"],
    cookingTime: "10 mins",
    calories: 280,
    emoji: "🥗",
    specialOffer: true,
  },
  {
    id: 2,
    name: "Hummus Paradise",
    price: 25000,
    image: "https://images.unsplash.com/photo-1571197119282-7c4e2b2d7c6b?w=600&h=400&fit=crop",
    description: "Creamy chickpea hummus served with warm pita bread and olive oil drizzle",
    category: "starters",
    rating: 4.6,
    reviews: 89,
    popular: false,
    vegetarian: true,
    ingredients: ["Chickpeas", "Tahini", "Lemon Juice", "Garlic", "Olive Oil", "Pita Bread"],
    cookingTime: "5 mins",
    calories: 320,
    emoji: "🧈",
  },
  {
    id: 3,
    name: "Dolmades Delight",
    price: 40000,
    image: "https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&h=400&fit=crop",
    description: "Grape leaves stuffed with rice, herbs, and Mediterranean spices",
    category: "starters",
    rating: 4.5,
    reviews: 67,
    popular: false,
    vegetarian: true,
    ingredients: ["Grape Leaves", "Rice", "Onions", "Dill", "Mint", "Pine Nuts"],
    cookingTime: "15 mins",
    calories: 180,
    emoji: "🍃",
  },
  {
    id: 4,
    name: "Tzatziki & Pita",
    price: 30000,
    image: "https://images.unsplash.com/photo-1563379091339-03246963d96a?w=600&h=400&fit=crop",
    description: "Cool yogurt dip with cucumber, garlic, and herbs served with warm pita",
    category: "starters",
    rating: 4.7,
    reviews: 156,
    popular: true,
    vegetarian: true,
    ingredients: ["Greek Yogurt", "Cucumber", "Garlic", "Dill", "Olive Oil", "Pita Bread"],
    cookingTime: "8 mins",
    calories: 220,
    emoji: "🥒",
  },
  {
    id: 5,
    name: "Spanakopita Triangles",
    price: 32000,
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&h=400&fit=crop",
    description: "Crispy phyllo pastry filled with spinach and feta cheese",
    category: "starters",
    rating: 4.4,
    reviews: 92,
    popular: false,
    vegetarian: true,
    ingredients: ["Phyllo Pastry", "Spinach", "Feta Cheese", "Onions", "Herbs"],
    cookingTime: "12 mins",
    calories: 250,
    emoji: "🥧",
  },
  {
    id: 6,
    name: "Greek Meatballs",
    price: 45000,
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&h=400&fit=crop",
    description: "Traditional keftedes with herbs and spices, served with tzatziki",
    category: "starters",
    rating: 4.6,
    reviews: 78,
    popular: true,
    ingredients: ["Ground Beef", "Herbs", "Onions", "Breadcrumbs", "Tzatziki"],
    cookingTime: "18 mins",
    calories: 380,
    emoji: "🍖",
  },

  // Mains
  {
    id: 7,
    name: "Moussaka Supreme",
    price: 85000,
    originalPrice: 95000,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=600&h=400&fit=crop",
    description: "Traditional layered dish with eggplant, seasoned ground lamb, and creamy béchamel sauce",
    category: "mains",
    rating: 4.9,
    reviews: 203,
    popular: true,
    ingredients: ["Eggplant", "Ground Lamb", "Béchamel Sauce", "Tomatoes", "Onions", "Cheese"],
    cookingTime: "45 mins",
    calories: 650,
    emoji: "🍆",
    specialOffer: true,
  },
  {
    id: 8,
    name: "Lamb Souvlaki",
    price: 75000,
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&h=400&fit=crop",
    description: "Grilled lamb skewers marinated in herbs, served with tzatziki and warm pita",
    category: "mains",
    rating: 4.8,
    reviews: 178,
    popular: true,
    spicy: true,
    ingredients: ["Lamb", "Oregano", "Lemon", "Garlic", "Tzatziki", "Pita Bread"],
    cookingTime: "25 mins",
    calories: 580,
    emoji: "🍢",
  },
  {
    id: 9,
    name: "Grilled Sea Bass",
    price: 95000,
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=400&fit=crop",
    description: "Fresh sea bass grilled with Mediterranean herbs and lemon, served with roasted vegetables",
    category: "mains",
    rating: 4.7,
    reviews: 134,
    popular: false,
    ingredients: ["Sea Bass", "Lemon", "Herbs", "Roasted Vegetables", "Olive Oil"],
    cookingTime: "30 mins",
    calories: 420,
    emoji: "🐟",
  },
  {
    id: 10,
    name: "Chicken Gyros",
    price: 65000,
    image: "https://images.unsplash.com/photo-1621852004158-f3bc188ace2d?w=600&h=400&fit=crop",
    description: "Marinated chicken wrapped in warm pita with fresh vegetables and tzatziki sauce",
    category: "mains",
    rating: 4.6,
    reviews: 245,
    popular: true,
    ingredients: ["Chicken", "Pita Bread", "Tomatoes", "Onions", "Tzatziki", "Lettuce"],
    cookingTime: "20 mins",
    calories: 520,
    emoji: "🌯",
  },
  {
    id: 11,
    name: "Vegetarian Moussaka",
    price: 70000,
    image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=600&h=400&fit=crop",
    description: "Plant-based version with layers of eggplant, lentils, and dairy-free béchamel",
    category: "mains",
    rating: 4.5,
    reviews: 98,
    popular: false,
    vegetarian: true,
    ingredients: ["Eggplant", "Lentils", "Cashew Cream", "Tomatoes", "Nutritional Yeast"],
    cookingTime: "40 mins",
    calories: 480,
    emoji: "🌱",
  },
  {
    id: 12,
    name: "Greek Style Pasta",
    price: 55000,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&h=400&fit=crop",
    description: "Pasta with olives, feta, tomatoes and Mediterranean herbs",
    category: "mains",
    rating: 4.4,
    reviews: 156,
    popular: false,
    vegetarian: true,
    ingredients: ["Pasta", "Olives", "Feta", "Tomatoes", "Herbs", "Olive Oil"],
    cookingTime: "22 mins",
    calories: 490,
    emoji: "🍝",
  },
  {
    id: 13,
    name: "Grilled Octopus",
    price: 90000,
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=400&fit=crop",
    description: "Tender grilled octopus with olive oil, lemon, and Mediterranean herbs",
    category: "mains",
    rating: 4.8,
    reviews: 89,
    popular: true,
    ingredients: ["Octopus", "Olive Oil", "Lemon", "Herbs", "Capers"],
    cookingTime: "35 mins",
    calories: 320,
    emoji: "🐙",
  },
  {
    id: 14,
    name: "Beef Stifado",
    price: 80000,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    description: "Slow-cooked beef stew with pearl onions and rich tomato sauce",
    category: "mains",
    rating: 4.6,
    reviews: 112,
    popular: false,
    ingredients: ["Beef", "Pearl Onions", "Tomatoes", "Wine", "Herbs"],
    cookingTime: "2 hours",
    calories: 620,
    emoji: "🍲",
  },

  // Desserts
  {
    id: 15,
    name: "Baklava Bliss",
    price: 35000,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&h=400&fit=crop",
    description: "Layers of crispy phyllo pastry with nuts and honey syrup",
    category: "desserts",
    rating: 4.9,
    reviews: 312,
    popular: true,
    vegetarian: true,
    ingredients: ["Phyllo Pastry", "Walnuts", "Pistachios", "Honey", "Cinnamon"],
    cookingTime: "5 mins",
    calories: 380,
    emoji: "🍯",
    specialOffer: true,
  },
  {
    id: 16,
    name: "Greek Yogurt Bowl",
    price: 25000,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop",
    description: "Thick Greek yogurt with honey, fresh fruits, and crushed nuts",
    category: "desserts",
    rating: 4.4,
    reviews: 87,
    popular: false,
    vegetarian: true,
    ingredients: ["Greek Yogurt", "Honey", "Fresh Berries", "Almonds", "Granola"],
    cookingTime: "3 mins",
    calories: 290,
    emoji: "🥣",
  },
  {
    id: 17,
    name: "Loukoumades",
    price: 30000,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop",
    description: "Golden honey puffs drizzled with honey and sprinkled with cinnamon",
    category: "desserts",
    rating: 4.6,
    reviews: 156,
    popular: true,
    vegetarian: true,
    ingredients: ["Flour", "Yeast", "Honey", "Cinnamon", "Sesame Seeds"],
    cookingTime: "15 mins",
    calories: 340,
    emoji: "🍩",
  },
  {
    id: 18,
    name: "Galaktoboureko",
    price: 40000,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=400&fit=crop",
    description: "Custard wrapped in crispy phyllo pastry with syrup",
    category: "desserts",
    rating: 4.7,
    reviews: 134,
    popular: false,
    vegetarian: true,
    ingredients: ["Phyllo", "Custard", "Milk", "Sugar", "Syrup"],
    cookingTime: "8 mins",
    calories: 420,
    emoji: "🥧",
  },
  {
    id: 19,
    name: "Rice Pudding",
    price: 22000,
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&h=400&fit=crop",
    description: "Creamy rice pudding with cinnamon and vanilla",
    category: "desserts",
    rating: 4.3,
    reviews: 76,
    popular: false,
    vegetarian: true,
    ingredients: ["Rice", "Milk", "Sugar", "Cinnamon", "Vanilla"],
    cookingTime: "5 mins",
    calories: 280,
    emoji: "🍚",
  },

  // Drinks
  {
    id: 20,
    name: "Greek Coffee",
    price: 15000,
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop",
    description: "Traditional strong Greek coffee served in a small cup",
    category: "drinks",
    rating: 4.3,
    reviews: 78,
    popular: false,
    ingredients: ["Greek Coffee", "Sugar", "Water"],
    cookingTime: "5 mins",
    calories: 5,
    emoji: "☕",
  },
  {
    id: 21,
    name: "Fresh Lemonade",
    price: 12000,
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&h=400&fit=crop",
    description: "Freshly squeezed lemon juice with mint and sparkling water",
    category: "drinks",
    rating: 4.5,
    reviews: 134,
    popular: true,
    vegetarian: true,
    ingredients: ["Fresh Lemons", "Mint", "Sparkling Water", "Sugar"],
    cookingTime: "2 mins",
    calories: 80,
    emoji: "🍋",
  },
  {
    id: 22,
    name: "Greek Wine",
    price: 45000,
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=400&fit=crop",
    description: "Premium Greek wine imported from the islands",
    category: "drinks",
    rating: 4.7,
    reviews: 89,
    popular: false,
    ingredients: ["Greek Grapes", "Natural Yeast"],
    cookingTime: "0 mins",
    calories: 125,
    emoji: "🍷",
  },
  {
    id: 23,
    name: "Frappé Coffee",
    price: 18000,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop",
    description: "Iced coffee Greek-style with foam and milk",
    category: "drinks",
    rating: 4.4,
    reviews: 167,
    popular: true,
    ingredients: ["Instant Coffee", "Sugar", "Milk", "Ice"],
    cookingTime: "3 mins",
    calories: 120,
    emoji: "🧊",
  },
  {
    id: 24,
    name: "Fresh Orange Juice",
    price: 14000,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&h=400&fit=crop",
    description: "Freshly squeezed orange juice packed with vitamin C",
    category: "drinks",
    rating: 4.2,
    reviews: 98,
    popular: false,
    vegetarian: true,
    ingredients: ["Fresh Oranges"],
    cookingTime: "2 mins",
    calories: 110,
    emoji: "🍊",
  },
  {
    id: 25,
    name: "Ouzo",
    price: 25000,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=400&fit=crop",
    description: "Traditional Greek anise-flavored spirit",
    category: "drinks",
    rating: 4.6,
    reviews: 67,
    popular: false,
    ingredients: ["Anise", "Herbs", "Alcohol"],
    cookingTime: "0 mins",
    calories: 80,
    emoji: "🥃",
  },
]

export const getFoodsByCategory = (category: string) => {
  if (category === "all") return foodDatabase
  return foodDatabase.filter((item) => item.category === category)
}

export const getPopularFoods = () => {
  return foodDatabase.filter((item) => item.popular).slice(0, 6)
}

export const getFoodById = (id: number) => {
  return foodDatabase.find((item) => item.id === id)
}

export const searchFoods = (query: string) => {
  return foodDatabase.filter(
    (item) =>
      item.name.toLowerCase().includes(query.toLowerCase()) ||
      item.description.toLowerCase().includes(query.toLowerCase()) ||
      item.ingredients.some((ingredient) => ingredient.toLowerCase().includes(query.toLowerCase())),
  )
}

export const getSpecialOffers = () => {
  return foodDatabase.filter((item) => item.specialOffer)
}
